### ISSUE TITLE
Unneeded dependency

### ISSUE THREAD

**Issue by snaens** [EduArt-Robotik/edu_drive#1]
[CMakeLists.txt](https://github.com/EduArt-Robotik/edu_drive/blob/iotbot2/CMakeLists.txt) (for the iotbot2 branch) contains mraa as a dependency, but mraa isn't used anywhere in this repo and everything compiles just fine if you comment out all lines mentioning mraa.

Is this intentional?

**Comment by stefanmay** [comment]
Thank you for reporting this issue. I have just fixed it.
