### ISSUE TITLE
(another) unneeded dependency

### ISSUE THREAD

**Issue by snaens** [EduArt-Robotik/edu_drive#2]
It seems that the `joy` package is included as a dependency, but isn't actually used anywhere in code.

*The ROS [joy(stick)](http://docs.ros.org/en/api/sensor_msgs/html/msg/Joy.html) message is part of `sensor_msgs`!
The `joy` package is for reading and publishing joysticks!*

This is troublesome since the `joy` package isn't part of the ROS default components so it needs to be installed, but it also has a large amount of dependencies.
This makes `edu_drive` annoying to use on embedded hardware, AKA robots ;)

**Comment by snaens** [comment]
#5 #4 #3

**Comment by stefanmay** [comment]
Thank you, I have merge the request.
